### ISSUE TITLE
Does threepipe or webgi support SSAA？

### ISSUE THREAD

**Issue by huanhunx** [repalash/threepipe#4]
Hello, I’m trying to build a scene using webgi. However, I’m not satisfied with the anti-aliasing effect of the engine. 
Is there a way to implement SSAA (Super-Sampling Anti-Aliasing) in webgi or Threepipe? I tried integrating Three.js’s SSAARenderPass as a plugin into my project, but it caused significant changes in the final display. After reading the renderpass source code of Threepipe, I noticed that a lot of work is being done there. 
Can Threepipe or webgi implement SSAARenderPass? Or is there a plan to add SSAA?

**Comment by repalash** [comment]
Hello, yes webgi has SSAA built-in  to ProgressivePlugin and you can see the effect when the camera stops. Since it's a multi frame effect, it's better to be done when the camera stops. But it is possible to do it in the same frame as in threejs but that would be very slow. So generally we use TAA when camera is moving and SSAA when it stops. 
The same implementation as webgi(SSAA and TAA) is being added to threepipe and will be available in a few days, will also add some docs regarding rendering in the same frame. 

Also there is msaa already in the viewer. You can try that as well

**Comment by repalash** [comment]
Hi, SSAAPlugin is now added to threepipe. 
You can try it in the editor or check the example here: https://threepipe.org/examples/#ssaa-plugin/
Increase the renders/frame in the UI for similar behaviour to three.js example
